name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./SV-CodingCase/SV-CodingCase.sln
    - name: Build
      run: dotnet build ./SV-CodingCase/SV-CodingCase.sln --no-restore
    - name: Test
      run: dotnet test ./SV-CodingCase/SV-CodingCase.sln --no-build --verbosity normal

    - name: Build the Docker image
      run: docker build --file ./SV-CodingCase/SV-CodingCase/Dockerfile --tag SV-CodingCase:$(date +%s)
